### ISSUE TITLE
Readme.md is a bit off :)

### ISSUE THREAD

**Issue by fitzee** [vschwaberow/adflib#17]
I needed to do something like the following:

```rust
use adflib::disk;   (instead of adflib::ADF)
``` 
_and_ 

```rust
let _adf = disk::ADF::from_file("test.adf");
```

Trivial, but thought I'd notify here.  -M

**Comment by vschwaberow** [comment]
Thanks. I will fix it.

**Comment by fitzee** [comment]
Actually.. just changing adflib::ADF to adflib::disk::ADF is sufficient :)
